### ISSUE TITLE
Network down after running

### ISSUE THREAD

**Issue by Blkzer0** [WiPi-Hunter/PiDense#2]
Hey i get this error after running the script, I wanted to test it so i set up a rouge ap on a different box but when i run the script, it doesn't show anything for about 5 mins and than i get the error that my network is down. Are there any kind of dependences that i might be missing?

Ran script on Parrot OS.

```
Information about test:
---------------------------------------------------------------
[*] Sun Mar 25 13:09:07 2018
[*] Analysis unencrypted network number and makes control
--- between unencrypted and encrypted wireless networks
---------------------------------------------------------------
Traceback (most recent call last):
  File "pidense.py", line 92, in <module>
    sniff_channel_hop(iface)
  File "pidense.py", line 35, in sniff_channel_hop
    sniff(iface=iface, count=15, prn=air_scan)
  File "/usr/lib/python2.7/dist-packages/scapy/sendrecv.py", line 610, in sniff
    p = s.recv()
  File "/usr/lib/python2.7/dist-packages/scapy/arch/linux.py", line 519, in recv
    pkt, sa_ll = self.ins.recvfrom(x)
socket.error: [Errno 100] Network is down
```

**Comment by besimaltnok** [comment]
Which hardware do you use as a network adapter? (TPLINK, Alfa ..) In addition, did you get into monitor mode with ( airmon-ng start with wlan0 )

NOTE: I also made updates. I will upload updates this week.

**Comment by Blkzer0** [comment]
yeah my adapter supports monitor mode, is this script dependent on specific hardware?

**Comment by besimaltnok** [comment]
Tool use scapy module for packet processing. if scapy module installed
Please, do instructions:

1- Plug hardware
2- Check hardware connection with iwconfig command
3- run airmon-ng check kill
4- run airmon-ng start wlan0 or wlan1 ..
5- Check again hardware connection with iwconfig
6- if set monitor mode, run python pidense.py -i [monitor mode interface] 

Finally, please contact with me from email: besimaltnok@gmail.com. Maybe I can help you better.

**Comment by jordantsap** [comment]
Plugin the ethernet cable before setting wifi to monitor mode
